config/routes.rb
Rails.application.routes.draw do

  root 'shows#index'

  get 'shows/:id/invalidate' => 'shows#invalidate', as: :invalidate
  get 'shows/invalidate_all' => 'shows#invalidate_all', as: :invalidate_all

  resources :shows do
    resources :episodes
  end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :show
  validates :no, presence: true
  validates :show_id, presence: true
  
  def self.view_start
    Date.today-3
  end
  def self.view_end
    Date.today+5
  end
  scope :upcoming, -> (time) { where("air_date >= ?", time) }
  scope :week_view, -> (r_start, r_end) { where("air_date >= ? and air_date <= ?", r_start, r_end) }
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :episodes, dependent: :destroy
  accepts_nested_attributes_for :episodes, allow_destroy: true
  
  validates :scrape_url, uniqueness: true, presence: true
  validates :name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @show = Show.find(params[:show_id])
    @episodes = @show.episodes.all
  end

  def create
    @show = Show.find(params[:show_id])
    @episode = @show.episodes.create(episode_params)
  end
  
  def destroy
    @show = Show.find(params[:show_id])
    @episode = @show.episodes.find(params[:id])
    @episode.destroy
    redirect_to show_episodes_path(@show)
  end
  
  def watched
    @show = Show.find(params[:show_id])
    redirect_to show_episodes_path(@show)
  end
  
  private
    def episode_params
      params.require(:episode).permit(:title, :no, :air_date, :air_time,
        :season, :channel, :watched, :show)
    end
end

app/controllers/shows_controller.rb
require 'open-uri'

class ShowsController < ApplicationController

  def index
    @shows = Show.all.sort { |x,y| x.name <=> y.name }
    @upcoming_episodes = Episode.upcoming(Date.today).order(:air_date, :air_time).first(10)
    episode_result = Episode.week_view(Episode.view_start,Episode.view_end).order(:air_date, :air_time)
    @episode_hash = {}
    (Episode.view_start..Episode.view_end).each { |day| @episode_hash[day] = [] }
    episode_result.each do |ep|
      @episode_hash[ep.air_date].push(ep)
    end
  end
  
  def new
    @show = Show.new
  end
  
  def create
    @show = Show.new(show_params)    
    if populate_episodes(@show)
      redirect_to @show
    else
      render 'new'
    end
  end
  
  def invalidate
    show = Show.find(params[:id])    
    if invalidate_episodes(show)
      redirect_to show_episodes_path(show)
    else
      render 'new'
    end
  end
  
  def invalidate_all
    Show.all.each do |show|
      invalidate_episodes(show)
    end
  end
  
  def show
    @show = Show.find(params[:id])
  end
  
  def edit
    @show = Show.find(params[:id])
  end
  
  def update
    @show = Show.find(params[:id])
    if @show.update(show_params)
      redirect_to :back
    else
      render 'edit'
    end
  end
  
  def destroy
    @show = Show.find(params[:id])
    @show.destroy
    redirect_to shows_path
  end
  
  private
    def show_params
      params.require(:show).permit(:name, :watch_url, :scrape_url, :genre,
                                   :episodes_attributes => [:id, :title, :no, :air_date, :air_time,
                                                            :season, :channel, :watched, :show])
    end
    
    # Scrapes a Wiki page with episode information
    def scrape_wiki(url)
      # Download Wiki Page
      page = Nokogiri::HTML(open(url))
      
      # Find tables with 'mw-content-ltr' class
      tables = page.xpath("//*/div/div/div[@class='mw-content-ltr']/table")

      tables_with_eps = Array.new
      headers_pos = Array.new

      # Search for 'Title', 'No' and 'Original air date' column headers
      # and save their location if the table has an 'Original air date' column
      tables.each do |table|
        i = 0
        is_eps_table = false
        headers = Hash.new
        table.xpath("./tr[1]/th").each do |th|
          if /(T|t)itle/ =~ th.text
            headers[:title] = i
          elsif /(N|n)o\./ =~ th.text
            unless /(N|n)o\. in (S|s)eries/ =~ th.text
              headers[:no] = i
            end
          elsif /(O|o)riginal (A|a)ir\s?(D|d)ate/ =~ th.text
            is_eps_table = true
            headers[:oad] = i
          end
          i += 1
        end
        if is_eps_table
          tables_with_eps << table
          headers_pos << headers
        end
      end
      
      # Extract the season name, episode number, ep title, and original air
      # date from each table and store in a hash of season hashes (containing
      # episode info
      seasons = Hash.new
      (0...tables_with_eps.size).each do |i|
        season_tmp = tables_with_eps[i].xpath("preceding-sibling::*[self::h6 or self::h5 or self::h4 or self::h3 or self::h2 or self::h1][1]/span[@class='mw-headline']")
        if season_tmp.empty?
          season_tmp = tables_with_eps[i].xpath("preceding-sibling::h2[1]/span[@class='mw-headline']")
        end
        season_name = season_tmp.text
        rows = tables_with_eps[i].css("tr.vevent")
        season = Hash.new
        rows.each do |row|
          columns = row.xpath("child::*")
          /(<.*?>)*"?(.*?)"?</.match(columns[headers_pos[i][:no]].to_s)
          no = $2
          if columns[headers_pos[i][:title]].xpath("child::a").empty?
            /"*([^"]+)"*/.match(columns[headers_pos[i][:title]].text)
            title = $1
          else
            /(.*?)$/.match(columns[headers_pos[i][:title]].xpath("child::a").text)
            title = $1
          end
          /(<.*?>)*"?(.*?)"?</.match(columns[headers_pos[i][:oad]].to_s)
          oad = $2
          season[no] = { :title => title, :oad => oad }
        end
        seasons[season_name] = season
      end

      return seasons
    end

    def invalidate_episodes(show)
      # Scrape URL for Episodes and prevent save if crash occurs
      ActiveRecord::Base.transaction do
        
        show.episodes.destroy_all
      # Save show and scraped episodes
      # Use ActiveRecord::Base.transaction to commit only once at the end
      
        if show.save
          seasons = scrape_wiki(show.scrape_url)
          seasons.keys.each do |season|
            seasons[season].keys.each do |no|
              ep = Episode.new(:title => seasons[season][no][:title], :no => no, 
                          :air_date => seasons[season][no][:oad], :air_time => nil, 
                          :season => season, :channel => nil, :watched => false, 
                          :show => show)
              ep.save
            end
          end
        else
          return false
        end
      end
      return true
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/episodes/index.html.erb
<h1><%= @show.name %> Episodes</h1>

<table class='showtable'>
  <tr>
    <th>No</th>
    <th>Title</th>
    <th>Air Date</th>
    <th>Season</th>
  </tr>
 
<% @episodes.each do |episode| %>
  <tr>
    <td><%= episode.no %></td>
    <td><%= episode.title %></td>
    <td><%= episode.air_date %></td>
    <td><%= episode.season %></td>
  </tr>
<% end %>
</table>

<p>
  <%= link_to 'Back to Shows', shows_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorganizer</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shows/_form.html.erb
<%= form_for @show do |f| %>
  <% if @show.errors.any? %>
  <div id="error_explanation">
    <h2 class='error'><%= pluralize(@show.errors.count, "error") %> prohibited
      this show from being saved:</h2>
    <ul>
    <% @show.errors.full_messages.each do |msg| %>
      <li class='error'><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :watch_url %><br>
    <%= f.text_field :watch_url %>
  </p>

  <p>
    <%= f.label :scrape_url %><br>
    <%= f.text_field :scrape_url %>
  </p>

  <p>
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shows/edit.html.erb
<h1>Edit <%= @show.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', shows_url %>
| <%= link_to 'View', show_path(@show) %>

app/views/shows/index.html.erb
<h1>Shows</h1>

<h2>Shows Directory</h2>

<table class='showtable'>
  <tr>
    <th>Name</th>
    <th>Genre</th>
    <th>Watch URL</th>
    <th>Scrape URL</th>
  </tr>
 
<% @shows.each do |show| %>
  <tr>
    <td><%= link_to show.name, show_episodes_path(show) %></td>
    <td><%= show.genre %></td>
    <td><%= link_to show.watch_url, show.watch_url, :target => '_blank' %></td>
    <td><%= link_to show.scrape_url, show.scrape_url, :target => '_blank' %></td>
    <td><%= link_to 'Show', show_path(show) %></td>
    <td><%= link_to 'Edit', edit_show_path(show) %></td>
    <td><%= link_to 'Delete', show_path(show),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>
<%= link_to 'Invalidate All Shows', invalidate_all_path, remote: true %>

<p>
  <%= link_to 'Add Show', new_show_path %>
</p>

<h2>Upcoming Schedule</h2>

<div class="displayWrapper">
  <table class="upcoming-table">
<% @episode_hash.keys.each do |day| %>
    <tr<%= (day == Date.today) ? ' class=today' : '' %>>
      <td class="day-column">
        <div><%= day.strftime("%m/%d %A") %></div>
      </td>
      <td class="show-column">
  <% @episode_hash[day].each do |ep| %>
        <div><%= link_to ep.show.name, show_episodes_path(ep.show) %></div>
  <% end %>
  <% if @episode_hash[day].empty? %>
        <em>None</em>
  <% end %>
      </td>
      <td class="episode-column">
  <% @episode_hash[day].each do |ep| %>
        <div><%= ep.title %></div>
  <% end %>
      </td>
    </tr>
<% end %>
  </table>
</div>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_url %>

app/views/shows/show.html.erb
<h1><%= @show.name %></h1>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Watch URL:</strong>
  <%= @show.watch_url %>
</p>

<p>
  <strong>Scrape URL:</strong>
  <%= @show.scrape_url %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @show.genre %>
</p>

<%= link_to 'Back', shows_url %>
| <%= link_to 'Edit', edit_show_path(@show) %>